BearingsWebApp/Controllers/MeebaInfoesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using BearingsWebApp.Models;
using Newtonsoft.Json;
using Microsoft.AspNet.Identity;

namespace BearingsWebApp.Controllers
{
    public class MeebaInfoesController : Controller
    {
        private BearingsWebAppContext db = new BearingsWebAppContext();
        // Integers that handle the Pull of the Meeba chart
        int userOuter = 1;
        int userInner = 1;
        
        // GET: MeebaInfoes
        //The Index holds and handles the Meeba chart
        
        [Authorize]
        public ActionResult Index()
        {
            // Each var is a base integer for the points of the Meeba
            // Each point is relative to a category filled in by the user
            var userAppt = 1;
            var userSocial = 1;
            var userWork = 1;
            var userPersonal = 1;
            var userEvent = 1;
            var userOther = 1;

            // Gets the Id of the current user
            // Then uses that ID to filter out data from other
            // Users and only gather the entries of the currently
            // Logged in User
            var currentUser = User.Identity.GetUserId();
            var userMeeba = from user in db.MeebaInfoes
                            where user.userID == currentUser
                            select user;
            
            // Each of the foreach methods applies the databse integers 
            // To the controller counterpart
            foreach (var appointment in userMeeba)
            {
                userAppt += appointment.apptInt;
            }

            foreach (var social in userMeeba)
            {
                userSocial += social.socInt;
            }

            foreach (var work in userMeeba)
            {
                userWork += work.workInt;
            }

            foreach (var personal in userMeeba)
            {
                userPersonal += personal.persInt;
            }

            foreach (var evt in userMeeba)
            {
                userEvent += evt.evtInt;
            }

            foreach (var other in userMeeba)
            {
                userOther += other.otherInt;
            }

            foreach (var inner in userMeeba)
            {
                userInner += inner.innerInt;
            }

            foreach (var outer in userMeeba)
            {
                userOuter += outer.OuterInt;
            }

            // Saves the controller integers to ViewData values
            // To be access via the view
            ViewData["Appointments"] = userAppt;
            ViewData["Social"] = userSocial;
            ViewData["Work"] = userWork;
            ViewData["Events"] = userEvent;
            ViewData["Personal"] = userPersonal;
            ViewData["Other"] = userOther;
            ViewData["Inner"] = userInner;
            ViewData["Outer"] = userOuter;
            return View(userMeeba.ToList()); 
        }

        // GET: MeebaInfoes/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            MeebaInfo meebaInfo = db.MeebaInfoes.Find(id);
            if (meebaInfo == null)
            {
                return HttpNotFound();
            }
            return View(meebaInfo);
        }

        // GET: MeebaInfoes/Create
        public ActionResult Create()
        {
            return View();

        }

        // POST: MeebaInfoes/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,itemName,category,pull,apptInt,workInt,socInt,evtInt,persInt,otherInt,innerInt,OuterInt")] MeebaInfo meebaInfo)
        {
            if (ModelState.IsValid)
            {

                db.MeebaInfoes.Add(meebaInfo);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(meebaInfo);
        }

        // GET: MeebaInfoes/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            MeebaInfo meebaInfo = db.MeebaInfoes.Find(id);
            if (meebaInfo == null)
            {
                return HttpNotFound();
            }
            return View(meebaInfo);
        }

        // POST: MeebaInfoes/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,itemName,category,pull,apptInt,workInt,socInt,evtInt,persInt,otherInt,innerInt,OuterInt")] MeebaInfo meebaInfo)
        {
            if (ModelState.IsValid)
            {
                db.Entry(meebaInfo).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(meebaInfo);
        }

        // GET: MeebaInfoes/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            MeebaInfo meebaInfo = db.MeebaInfoes.Find(id);
            if (meebaInfo == null)
            {
                return HttpNotFound();
            }
            return View(meebaInfo);
        }

        // POST: MeebaInfoes/Delete/5
        // Passes the id, category, and pull of the selected 
        // Database object to the controller for deletion
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id, string category, string pull)
        {
           
            MeebaInfo meebaInfo = db.MeebaInfoes.Find(id);

            // Runs a switch statement with the category passed in
            // That will decrement the value of that category from the Meeba
            // If the object is holds the category 
            switch (category)
            {
                case "Social":
                    meebaInfo.socInt--;
                    break;

                case "Appointment":
                    meebaInfo.apptInt--;
                    break;

                case "Work":
                    meebaInfo.workInt--;
                    break;

                case "Events":
                    meebaInfo.evtInt--;
                    break;

                case "Other":
                    meebaInfo.otherInt--;
                    break;

                case "Personal":
                    meebaInfo.persInt--;
                    break;

            }

            switch (pull)
            {
                case "Inner":
                    meebaInfo.innerInt--;
                    break;

                case "Outer":
                    meebaInfo.OuterInt--;
                    break;
            }

            db.MeebaInfoes.Remove(meebaInfo);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        // Passes the users input from the View back to the controller 
        // To be saved into the database
        // However, if it is not a valid input
        // The user will be redirected to an error page 
        public ActionResult PostEvent([Bind(Include = "ID,itemName,category,pull")]MeebaInfo meeba)
        {
            // Passes the category into the switch statement
            // If the category is matches a case, it will increment
            // That category in the database
            switch (meeba.category)
            {
                case "Social":
                    meeba.socInt++;
                    break;

                case "Appointment":
                    meeba.apptInt++;
                    break;

                case "Work":
                    meeba.workInt++;
                    break;

                case "Events":
                    meeba.evtInt++;
                    break;

                case "Other":
                    meeba.otherInt++;
                    break;

                case "Personal":
                    meeba.persInt++;
                    break;

            }
            //Gets a list of inputs for the user
            //Based on the currently logged in user
            
            var currentUser = User.Identity.GetUserId();
            var userMeeba = from user in db.MeebaInfoes
                            where user.userID == currentUser
                            select user;

            // Applies the integer for inner and outer
            // Based on the integers in the database
            foreach (var outer in userMeeba)
            {
                userOuter += outer.OuterInt;
            }
            foreach (var inner in userMeeba)
            {
                userInner += inner.innerInt;
            }

            // Applies the integers to a ViewData value
            // To be accessed by the View
            ViewData["Outer"] = userOuter;
            ViewData["Inner"] = userInner;

          // Passes the pull into the switch statement
          // If the pull matches the case, increment 
          // The pull, and decrement its opposite
          // Value, so long as that value is greater 
          // Than 1
            switch (meeba.pull)
            {
                case "Outer":
                    meeba.OuterInt++;
                    if (userInner > 1)
                    {

BearingsWebApp/Views/Shared/_Layout.cshtml
@{
    ViewBag.Title = "How To Use";
}


<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <link rel="stylesheet" href="animate.min.css">

    <style>
        /* The Modal (background) */
        .modal {
            display: none; /* Hidden by default */
            position: fixed; /* Stay in place */
            z-index: 1; /* Sit on top */
            padding-top: 100px; /* Location of the box */
            left: 0;
            top: 0;
            width: 100%; /* Full width */
            height: 100%; /* Full height */
            overflow: auto; /* Enable scroll if needed */
            background-color: rgb(0,0,0); /* Fallback color */
            background-color: rgba(0,0,0,0.4); /* Black w/ opacity */
        }

        /* Modal Content */
        .modal-content {
            background-color:white;
            margin: auto;
            padding: 20px;
            border: 1px solid #888;
            width: 80%;
        }

        /* The Close Button */
        .close {
            color: #aaaaaa;
            float: right;
            font-size: 28px;
            font-weight: bold;
        }

            .close:hover,
            .close:focus {
                color: #000;
                text-decoration: none;
                cursor: pointer;
            }
    </style>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.6.0/Chart.min.js">
    </script>


</head>
<body>
    <div class="navbar navbar-default navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target=".navbar-collapse" aria-expanded="false" aria-controls="navbar">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="#"></a>
            </div>
            <div id="navbar" class="navbar-collapse collapse">
                <button type="button" class="btn btn-default navbar-btn" id="myBtn">How To Use</button>
                <button class="btn navbar-btn dropdown-toggle" id="dropdownMenu1" data-toggle="dropdown" aria-expanded="true">
                    <span class="glyphicon glyphicon-th-list"></span>
                </button>
                <ul class="dropdown-menu" role="menu" aria-labelledby="dropdownMenu1" id="myList">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li role="separator" class="divider"></li>
                    <li>@Html.ActionLink("FAQ", "About", "Home")</li>
                    <li role="separator" class="divider"></li>
                    <li>@Html.ActionLink("Your Meeba", "Index", "MeebaInfoes")</li>
                </ul>
                
                @Html.Partial("_LoginPartial")
                </div>
                <!-- The Modal -->
                <div id="myModal" class="modal">

                    <!-- Modal content -->
                    <div class="modal-content animated fadeIn">
                        <span class="close">&times;</span>
                        <p><b>How To Create A Profile:</b> To create a profile, you can manually input your own username and password or you can register through your Google account.
                         *Note: the password must be at least 6 characters long and include at least one number and one special character (!#$% etc.).</p>
                        <p><b>How do I read the Meeba (the scale)?</b> Your Meeba has two scales. one called <b>Pull</b> that will measure your <i> Inner / Outer</i> skew. 
                        The second is called <b>Categories</b> that will show you how much time you're giving to the different areas of your life.</p>
                        <p> <b> Pull</b> and <b>Categories</b> scales and to keep your <i>Inner / Outer</i> pull as balanced as possible.</p>
                        <p><b>What is Pull? (<i>Inner / Outer</i>) </b><i>Pull</i> references how much the activities you enter are skewed towards <i>Inner / Outer</i> spectrum.
                         refrences how much the activities you enter are "skewed" towards the inner or outer spectrum</p>
                        <p><b><i>Inner/Outer</i></b> These represnt tasks that are either part of your personal well being or your social well being. 
                        <i>Inner</i> represents any event or activity that you do for yourself. It could be a walk, a night out with friends, an hour of reading or anything that benefits you directly.
                         <i>Outer</i> represents any event or activity that you do for others. This includes work, school projects, running errands for the benefit of others.</p>
                        <p><b>What Are All These Catagories?</b> These are put here to help you figure out where your task best fits. When you create a new task, choose a category that best aligns to tasks in your own life.</p>
                        <p><b>How Do I Delete Info (Remove Completed or Unwanted Tasks?)</b> Go to <i>Create Event</i> Select <i>Delete</i></p>
                        <p><b>How Do I Use Meeba?</b>We know that no two lives are the same,so youre idea of balanced my be diffrent from what we have set for defaults.However,the goal is to remain as close to your personal balance as possible.
                        If you have too many things pulling your life to the Inner(Personal) you may want to pay more attention to the things you have scheduled for your Outer(social) and vice versa. </p>

                    </div>
                 

                   
                </div><!--/.nav-collapse -->
        </div>
    </div>
    <div class="container">
        @RenderBody()
        <hr />
    </div>
        <footer class="container">
            <p>&copy; @DateTime.Now.Year - Bearings</p>
        </footer>
    


    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
    <script>
// Get the modal
var modal = document.getElementById('myModal');

// Get the button that opens the modal
var btn = document.getElementById("myBtn");

// Get the <span> element that closes the modal
var span = document.getElementsByClassName("close")[0];

// When the user clicks the button, open the modal
btn.onclick = function() {
    modal.style.display = "block";
}

// When the user clicks on <span> (x), close the modal
span.onclick = function() {
    modal.style.display = "none";
}

// When the user clicks anywhere outside of the modal, close it
window.onclick = function(event) {
    if (event.target == modal) {
        modal.style.display = "none";
    }
}
    </script>
</body>
</html>
 